version: '3'

services:
  whatsapp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-node
    restart: always
    volumes:
      - /home/drakarin/whatsapp.drakarin.com.br:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
